# Exercises

# Overview

## For each of the following questions, formulate a null and alternative hypothesis (be as specific as you can be), 
## then give an example of what a true positive, true negative, type I and type II errors would look like.

### Is the website redesign any good? 

### Rephrased: Has the click rate gone up, down, or stayed the same since the website redesign?
    
   **Null hypothesis:** The click rate on the website has remained the same since the redesign.
    
   **Alternative hypothesis:** The website redesign was terrible and had a negative affect on the click rate.
    
   **True Positive:** Null hypothesis rejected and website redisign has had a negative affect on the click rate.
    
   **True Negative:** Null hypothesis not rejected.  Website redisign had a positive affect on click rates.
    
   **Type 1 Error:** Results say that website redesign had a negative affect on click rates but actually didnt in reality.
    
   **Type 2 Error:** Results say that website redesign didn't have a negative affect but it actually did in reality.
    

### Is our television ad driving more sales?

### Rephrased: Have sales gone up, down, or stayed the same since the release of our adds?
    
   **Null hypothesis:** The adds have no proven causal affect on our sales.
    
   **Alternative hypothesis:** The adds have had a positive affect on our sales.
    
   **True Positive:** Adds have a positive affect on sales.
    
   **True Negative:** Adds aren't proven to have a positive affect on sales.
    
   **Type 1 Error:** Results say that adds have a positive affect while in reality it didn't.
    
   **Type 2 Error:** Results say that adds don't have a positive affect on sales while in reality it does.

### Has the network latency gone up since we switched internet service providers?

### Rephrased: How has our network latency changed since we switched internet service providers?
    
   **Null hypothesis:** The change of internet service provider has had no affect on our latency.
    
   **Alternative hypothesis:** The change of internet service provider has increased our latency.
    
   **True Positive:** Change of ISP increased latency.
    
   **True Negative:** No proof that change of ISP had the affect of increasing latency.
    
   **Type 1 Error:** Results say that change of ISP increased latency while in reality it did not.
    
   **Type 2 Error:** Results say that change of ISP had no affect on latency while in reality it did.

# T-Test

### Ace Realty wants to determine whether the average time it takes to sell homes is different for its two offices. A sample of 40 sales from office #1 revealed a mean of 90 days and a standard deviation of 15 days. A sample of 50 sales from office #2 revealed a mean of 100 days and a standard deviation of 20 days. Use a .05 level of significance.

In [1]:
import math
import numpy as np
from scipy import stats

In [2]:
stats.norm(90, 15).rvs(40)

array([105.41821591,  87.6938362 , 107.5221745 ,  76.77012587,
        98.63629663,  85.20465595, 100.26804285,  98.10939313,
        73.15511749,  72.76090906,  79.48108091,  93.8110528 ,
       102.70715087, 104.55149173,  99.53853525,  75.13498987,
       108.3767164 , 101.46687317,  92.23894567, 112.01373518,
        89.10052489,  99.13353006,  98.60479716,  91.08100177,
       122.1630188 , 112.89703593,  86.02680903,  99.25295137,
        92.03106919,  63.1433608 ,  62.65516149,  97.92722044,
        91.20208791,  72.70775364, 101.73326916, 112.93188153,
        98.55587253,  75.67644106, 104.78252044, 102.94600199])

In [3]:
stats.norm(100, 20).rvs(50)

array([100.78555795,  93.79656017, 125.2707343 , 117.01230097,
        83.12316182, 106.39088811, 119.14827014,  95.90235512,
       104.98828772,  85.21912139, 105.74549339, 111.48413365,
        74.53534201, 125.86693012, 134.89945492,  86.12639366,
        87.13320493, 110.89829725, 116.11885987, 106.74565539,
        91.98400146, 114.78800254,  72.59737393,  93.81399873,
       105.8509507 , 123.51192867,  95.42989013, 118.21212676,
        89.05550167,  61.89103618, 117.39771186, 105.80181267,
       104.70323743,  93.68940079, 147.15570317,  83.82793009,
       122.45237508,  85.66972201, 130.27066895,  80.42130181,
       113.37210697, 115.71919572, 129.1311827 , 111.26426783,
       147.53317932, 111.43280804,  92.66584326, 117.93867103,
       114.16864025, 109.72765039])

In [4]:
α = .05 #level of signifigance

n1 = 40 #sales
n2 = 50 #sales

µ1 = 90 #days
µ2 = 100 #days

σ1 = 15 #days
σ2 = 20 #days

x1 = stats.norm(90, 15).rvs(40)
x2 = stats.norm(100, 20).rvs(50)

x̄1 = x1.mean()
x̄2 = x2.mean()

s1 = x1.std()
s2 = x2.std()

degf = n1 + n2 - 2

sp = math.sqrt(((n1 - 1)*(σ1 ** 2) + (n2 - 1)*(σ2 ** 2)) / (degf))

t = (x̄1 - x̄2) / (sp * math.sqrt(1/n1 + 1/n2))

standard_error = se = math.sqrt(s1**2 / n1 + s2**2 / n2)

In [5]:
p = stats.t(degf).cdf(t) * 2
p

0.00546755614977545

In [6]:
t

-2.848532090920266

In [7]:
stats.ttest_ind(x1, x2)

Ttest_indResult(statistic=-2.7325325841087786, pvalue=0.007595353548288192)

### Load the mpg dataset and use it to answer the following questions:

In [8]:
from pydataset import data

mpg = data('mpg')
mpg

manufacturer                   model  displ  year  cyl       trans drv  \
1           audi                      a4    1.8  1999    4    auto(l5)   f   
2           audi                      a4    1.8  1999    4  manual(m5)   f   
3           audi                      a4    2.0  2008    4  manual(m6)   f   
4           audi                      a4    2.0  2008    4    auto(av)   f   
5           audi                      a4    2.8  1999    6    auto(l5)   f   
6           audi                      a4    2.8  1999    6  manual(m5)   f   
7           audi                      a4    3.1  2008    6    auto(av)   f   
8           audi              a4 quattro    1.8  1999    4  manual(m5)   4   
9           audi              a4 quattro    1.8  1999    4    auto(l5)   4   
10          audi              a4 quattro    2.0  2008    4  manual(m6)   4   
11          audi              a4 quattro    2.0  2008    4    auto(s6)   4   
12          audi              a4 quattro    2.8  1999    6    auto(l5)   4   
13          audi              a4 quattro    2.8  1999    6  manual(m5)   4   
14          audi              a4 quattro    3.1  2008    6    auto(s6)   4   
15          audi              a4 quattro    3.1  2008    6  manual(m6)   4   
16          audi              a6 quattro    2.8  1999    6    auto(l5)   4   
17          audi              a6 quattro    3.1  2008    6    auto(s6)   4   
18          audi              a6 quattro    4.2  2008    8    auto(s6)   4   
19     chevrolet      c1500 suburban 2wd    5.3  2008    8    auto(l4)   r   
20     chevrolet      c1500 suburban 2wd    5.3  2008    8    auto(l4)   r   
21     chevrolet      c1500 suburban 2wd    5.3  2008    8    auto(l4)   r   
22     chevrolet      c1500 suburban 2wd    5.7  1999    8    auto(l4)   r   
23     chevrolet      c1500 suburban 2wd    6.0  2008    8    auto(l4)   r   
24     chevrolet                corvette    5.7  1999    8  manual(m6)   r   
25     chevrolet                corvette    5.7  1999    8    auto(l4)   r   
26     chevrolet                corvette    6.2  2008    8  manual(m6)   r   
27     chevrolet                corvette    6.2  2008    8    auto(s6)   r   
28     chevrolet                corvette    7.0  2008    8  manual(m6)   r   
29     chevrolet         k1500 tahoe 4wd    5.3  2008    8    auto(l4)   4   
30     chevrolet         k1500 tahoe 4wd    5.3  2008    8    auto(l4)   4   
31     chevrolet         k1500 tahoe 4wd    5.7  1999    8    auto(l4)   4   
32     chevrolet         k1500 tahoe 4wd    6.5  1999    8    auto(l4)   4   
33     chevrolet                  malibu    2.4  1999    4    auto(l4)   f   
34     chevrolet                  malibu    2.4  2008    4    auto(l4)   f   
35     chevrolet                  malibu    3.1  1999    6    auto(l4)   f   
36     chevrolet                  malibu    3.5  2008    6    auto(l4)   f   
37     chevrolet                  malibu    3.6  2008    6    auto(s6)   f   
38         dodge             caravan 2wd    2.4  1999    4    auto(l3)   f   
39         dodge             caravan 2wd    3.0  1999    6    auto(l4)   f   
40         dodge             caravan 2wd    3.3  1999    6    auto(l4)   f   
41         dodge             caravan 2wd    3.3  1999    6    auto(l4)   f   
42         dodge             caravan 2wd    3.3  2008    6    auto(l4)   f   
43         dodge             caravan 2wd    3.3  2008    6    auto(l4)   f   
44         dodge             caravan 2wd    3.3  2008    6    auto(l4)   f   
45         dodge             caravan 2wd    3.8  1999    6    auto(l4)   f   
46         dodge             caravan 2wd    3.8  1999    6    auto(l4)   f   
47         dodge             caravan 2wd    3.8  2008    6    auto(l6)   f   
48         dodge             caravan 2wd    4.0  2008    6    auto(l6)   f   
49         dodge       dakota pickup 4wd    3.7  2008    6  manual(m6)   4   
50         dodge       dakota pickup 4wd    3.7  2008    6    auto(l4)   4   
51         dodge       dak

### Is there a difference in fuel-efficiency in cars from 2008 vs 1999?

In [9]:
# Fuel efficiency of cars from 1999

mpg_1999 = ((mpg.cty[mpg.year == 1999] + mpg.hwy[mpg.year == 1999]) / 2)

# Fuel efficiency of cars from 2008

mpg_2008 = (mpg.cty[mpg.year == 2008] + mpg.hwy[mpg.year == 2008])

stats.ttest_ind(mpg_1999, mpg_2008)

Ttest_indResult(statistic=-19.399034424839172, pvalue=1.815311826660654e-50)

### Are compact cars more fuel-efficient than the average car?

In [10]:
# Fuel efficiency of compact cars

mpg_compact = (mpg.cty[mpg['class'] == 'compact'] + mpg.hwy[mpg['class'] == 'compact'] / 2)

# Fuel efficiency of all cars

mpg_all = ((mpg.cty + mpg.hwy) / 2).mean()

stats.ttest_1samp(mpg_compact, mpg_all)

Ttest_1sampResult(statistic=18.624517190434428, pvalue=4.67400197211997e-23)

### Do manual cars get better gas mileage than automatic cars?

In [11]:
mpg.trans = mpg.trans.str[:-4]

In [12]:
manual_mpg = (mpg[mpg.trans == 'manual'].cty +  mpg[mpg.trans == 'manual'].hwy) / 2

In [13]:
auto_mpg = (mpg[mpg.trans == 'auto'].cty +  mpg[mpg.trans == 'auto'].hwy) / 2

In [14]:
stats.ttest_ind(auto_mpg, manual_mpg)

Ttest_indResult(statistic=-4.593437735750014, pvalue=7.154374401145683e-06)

# Correlation

### Use the telco_churn data. Does tenure correlate with monthly charges? Total charges? What happens if you control for phone and internet service?

In [15]:
import pandas as pd
data = pd.read_csv("Telco_Data.csv") 
data.head()

customer_id  gender  is_senior_citizen partner dependents  phone_service  \
0  0002-ORFBO  Female                  0     Yes        Yes              1   
1  0003-MKNFE    Male                  0      No         No              2   
2  0004-TLHLJ    Male                  0      No         No              1   
3  0011-IGKFF    Male                  1     Yes         No              1   
4  0013-EXCHZ  Female                  1     Yes         No              1   

   internet_service  contract_type      payment_type monthly_charges  ...  \
0                 1              1      Mailed check          $65.60  ...   
1                 1              0      Mailed check          $59.90  ...   
2                 2              0  Electronic check          $73.90  ...   
3                 2              0  Electronic check          $98.00  ...   
4                 2              0      Mailed check          $83.90  ...   

  has_phone has_internet  has_phone_and_internet  partner_dependents  \
0      True         True                    True                   3   
1      True         True                    True                   0   
2      True         True                    True                   0   
3      True         True                    True                   1   
4      True         True                    True                   1   

   start_date  avg_monthly_charges  contract_type2     phone_service2  \
0      1/7/19               $65.92          1 Year           One Line   
1      1/7/19               $60.27  Month-to-Month  Two or More Lines   
2      6/7/19               $70.21  Month-to-Month           One Line   
3      9/7/18               $95.22  Month-to-Month           One Line   
4      7/7/19               $89.13  Month-to-Month           One Line   

   Internet_service2 End Date  
0                DSL  10/7/19  
1                DSL  10/7/19  
2        Fiber Optic  10/7/19  
3        Fiber Optic  10/7/19  
4        Fiber Optic  10/7/19  

[5 rows x 25 columns]

In [16]:
tenure = data.Monthly_Tenure
monthly_charges = data.monthly_charges
#stats.ttest_ind(tenure, monthly_charges)

In [17]:
# corr, p = stats.pearsonr(tenure, monthly_charges)
# corr, p

### Use the employees database.



In [42]:
import pandas as pd
from env import user, host, password

def get_db_url(user, host, password, database):
    url = f'mysql+pymysql://{user}:{password}@{host}/{database}'
    return url

employees_url = get_db_url(user, host, password, database="employees")

employees = pd.read_sql('''SELECT
    e.*,
    datediff('2002-09-30', e.hire_date) tenure,
    t.title,
    t.from_date title_from,
    datediff('2002-09-30', t.from_date) t_tenure,
    et.titles,
    s.salary,
    s.from_date salary_from,
    datediff('2002-09-30', s.from_date) s_tenure,
    es.salaries
FROM
    employees e
JOIN 
    titles t 
    USING(emp_no)
JOIN 
    salaries s 
    USING(emp_no)
JOIN
    (SELECT 
        emp_no,
        count(*) titles
    FROM
        titles
    GROUP BY
        emp_no) et
    USING(emp_no)
JOIN
    (SELECT 
        emp_no,
        count(*) salaries
    FROM
        salaries
    GROUP BY
        emp_no) es
    USING(emp_no)
WHERE
    s.to_date > '2002-09-30'
    AND t.to_date > '2002-09-30';
''', employees_url)

print(employees.shape)
print(employees.dtypes)
employees.sample(5)

(240124, 15)
emp_no          int64
birth_date     object
first_name     object
last_name      object
gender         object
hire_date      object
tenure          int64
title          object
title_from     object
t_tenure        int64
titles          int64
salary          int64
salary_from    object
s_tenure        int64
salaries        int64
dtype: object


emp_no  birth_date first_name    last_name gender   hire_date  tenure  \
150081  287328  1954-07-07      Ennio  Keustermans      M  1987-02-18    5703   
37452    56661  1954-09-05      Navid    Kornatzky      M  1990-04-13    4553   
33043    51156  1953-03-22      Vatsa        Peron      M  1992-08-10    3703   
187135  433739  1956-07-28      Sadun         Pena      F  1985-12-08    6140   
198566  447997  1961-06-19   Radoslaw      Thummel      M  1988-02-04    5352   

                  title  title_from  t_tenure  titles  salary salary_from  \
150081  Senior Engineer  1997-05-07      1972       2   73970  2002-05-05   
37452      Senior Staff  1995-04-13      2727       2   77039  2002-04-10   
33043          Engineer  1999-04-28      1251       1   45517  2002-04-27   
187135     Senior Staff  1994-03-18      3118       2   79780  2002-03-15   
198566     Senior Staff  1988-02-04      5352       1   65567  2002-01-31   

        s_tenure  salaries  
150081       148        12  
37452        173        13  
33043        156         4  
187135       199        14  
198566       242        15

### Is there a relationship between how long an employee has been with the company and their salary?

In [19]:
stats.ttest_ind(employees.t_tenure, employees.salary)

Ttest_indResult(statistic=-1965.290256976851, pvalue=0.0)

In [20]:
corr, p = stats.pearsonr(employees.t_tenure, employees.salary)
corr, p

(0.2928925355455215, 0.0)

### Is there a relationship between how long an employee has been with the company and the number of titles they have had?

In [21]:
stats.ttest_ind(employees.t_tenure, employees.titles)

Ttest_indResult(statistic=823.4102997009813, pvalue=0.0)

In [22]:
corr, p = stats.pearsonr(employees.t_tenure, employees.titles)
corr, p

(-0.3130073440315879, 0.0)

### Use the sleepstudy data. Is there a relationship between days and reaction time?

In [23]:
from pydataset import data
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

sleepstudy = data('sleepstudy')
sleepstudy.head()

Reaction  Days  Subject
1  249.5600     0      308
2  258.7047     1      308
3  250.8006     2      308
4  321.4398     3      308
5  356.8519     4      308

In [24]:
stats.ttest_ind(sleepstudy.Days, sleepstudy.Reaction)

Ttest_indResult(statistic=-69.93555875916752, pvalue=7.790453448409e-211)

In [25]:
corr, p = stats.pearsonr(sleepstudy.Days, sleepstudy.Reaction)
corr, p

(0.5352302262650253, 9.894096322214812e-15)

# Chi Square

### Use the following contingency table to help answer the question of whether using a macbook and being a codeup student are independent of each other.



|                       | Codeup Student | Not Codeup Student |   |   |
|-----------------------|----------------|--------------------|---|---|
| Uses A Macbook        | 49             | 20                 |   |   |
| Doesn't Use A MacBook | 1              | 30                 |   |   |
|                       |                |                    |   |   |

$H_{0}$: Whether or not someone uses a macbook is independent of being a codeup student

$H_{a}$: Whether or not someone uses a macbook is NOT independent of being a codeup student

In [26]:
index = ['Uses A Macbook', "Doesn't Use A Macbook"]
columns = ['Codeup Student', 'Not Codeup Student']

observed = pd.DataFrame([[49, 20], [1, 30]], index=index, columns=columns)
chi2, p, degf, expected = stats.chi2_contingency(observed)
print('Observed\n')
print(observed.values)
print('---\nExpected\n')
print(expected)
print('---\n')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed

[[49 20]
 [ 1 30]]
---
Expected

[[34.5 34.5]
 [15.5 15.5]]
---

chi^2 = 36.6526
p     = 0.0000


#### <font color='red'>The two variables are not independent</font>

### Choose another 2 categorical variables from the mpg dataset and perform a chi^2 contingency table test with them. Be sure to state your null and alternative hypotheses.

$H_{0}$: Whether or not the class of car is a compact is independent of whether or not it's an Audi.

$H_{a}$: Whether or not the class of car is a compact is NOT independent of whether or not it's an Audi.

In [27]:
# compact = (mpg['class'][mpg.manufacturer == 'audi'] == 'compact').sum()
# not_compact = (mpg['class'][mpg.manufacturer == 'audi'] != 'compact').sum()

compact = (mpg['class'] == 'compact').sum()
not_compact = (mpg['class'] != 'compact').sum()
audi = (mpg.manufacturer == 'audi').sum()
not_audi = (mpg.manufacturer != 'audi').sum()

In [28]:
index_mpg = ['Compact', 'Not A Compact']
columns_mpg = ['Audi', 'Not Audi']
observed_mpg = pd.DataFrame([[compact, not_compact], [audi, not_audi]], index=index_mpg, columns=columns_mpg)
observed_mpg

Audi  Not Audi
Compact          47       187
Not A Compact    18       216

In [29]:
chi2, p, degf, expected = stats.chi2_contingency(observed_mpg)

print('Observed\n')
print(observed_mpg.values)
print('---\nExpected\n')
print(expected)
print('---\n')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed

[[ 47 187]
 [ 18 216]]
---
Expected

[[ 32.5 201.5]
 [ 32.5 201.5]]
---

chi^2 = 14.0069
p     = 0.0002


#### <font color='red'>The two variables are not independent</font>

## Use the data from the employees database to answer these questions:

In [30]:
print(employees.shape)
print(employees.dtypes)
employees.sample(5)

(240124, 15)
emp_no          int64
birth_date     object
first_name     object
last_name      object
gender         object
hire_date      object
tenure          int64
title          object
title_from     object
t_tenure        int64
titles          int64
salary          int64
salary_from    object
s_tenure        int64
salaries        int64
dtype: object


emp_no  birth_date first_name last_name gender   hire_date  tenure  \
36782    55820  1963-03-28      Tonny   Cannard      F  1991-06-18    4122   
62718    88222  1956-04-26    Karsten   Geffroy      F  1986-08-13    5892   
188019  434846  1957-07-16      Basem  Collette      F  1987-09-14    5495   
162368  402723  1960-04-25     Vivian    Mahmud      M  1993-07-15    3364   
176083  419881  1959-01-02      Navin    Winter      F  1985-09-17    6222   

               title  title_from  t_tenure  titles  salary salary_from  \
36782   Senior Staff  1997-06-17      1931       2   75592  2002-06-15   
62718   Senior Staff  1997-02-20      2048       2  102996  2002-02-17   
188019  Senior Staff  1992-09-13      3669       2  106430  2001-09-10   
162368         Staff  1996-11-14      2146       1   64182  2001-11-13   
176083  Senior Staff  1994-09-17      2935       2   96230  2001-09-13   

        s_tenure  salaries  
36782        107        12  
62718        225        15  
188019       385        15  
162368       321         6  
176083       382        17

### Is an employee's gender independent of whether an employee works in sales or marketing? (only look at current employees)

$H_{0}$: Employee's gender is independent of whether an employee works in sales or marketing.

$H_{a}$: Employee's gender is not independent of whether an employee works in sales or marketing.

In [62]:
employees_female_by_department = pd.read_sql('''select departments.dept_no, departments.dept_name, count(employees.emp_no) as count
from departments
join dept_emp
on departments.dept_no = dept_emp.dept_no
join employees
on dept_emp.emp_no = employees.emp_no
where dept_emp.to_date = '9999-01-01' and gender = 'F'
group by departments.dept_name
order by dept_no;
''',employees_url)

print(employees_female_by_department.shape)
print(employees_female_by_department.dtypes)
employees_female_by_department

(9, 3)
dept_no      object
dept_name    object
count         int64
dtype: object


dept_no           dept_name  count
0    d001           Marketing   5864
1    d002             Finance   5014
2    d003     Human Resources   5147
3    d004          Production  21393
4    d005         Development  24533
5    d006  Quality Management   5872
6    d007               Sales  14999
7    d008            Research   6181
8    d009    Customer Service   7007

In [79]:
females_sales_or_marketing = 5864 +14999
females_not = employees_female_by_department['count'].sum() - females_sales_or_marketing
females_not

75147

In [63]:
employees_male_by_department = pd.read_sql('''select departments.dept_no, departments.dept_name, count(employees.emp_no) as count
from departments
join dept_emp
on departments.dept_no = dept_emp.dept_no
join employees
on dept_emp.emp_no = employees.emp_no
where dept_emp.to_date = '9999-01-01' and gender = 'M'
group by departments.dept_name
order by dept_no;
''',employees_url)

print(employees_male_by_department.shape)
print(employees_male_by_department.dtypes)
employees_male_by_department

(9, 3)
dept_no      object
dept_name    object
count         int64
dtype: object


dept_no           dept_name  count
0    d001           Marketing   8978
1    d002             Finance   7423
2    d003     Human Resources   7751
3    d004          Production  31911
4    d005         Development  36853
5    d006  Quality Management   8674
6    d007               Sales  22702
7    d008            Research   9260
8    d009    Customer Service  10562

In [76]:
males_sales_or_marketing = 8978 + 22702
males_not = employees_male_by_department['count'].sum() - males_sales_or_marketing
males_not

112434

In [68]:
sales_or_marketing = males_sales_or_marketing + females_sales_or_marketing

In [78]:
index_emp = ['Male', 'Female']
columns_emp = ['Sales or Marketing', 'Not Sales or Marketing']
observed_emp = pd.DataFrame([[males_sales_or_marketing, males_not], [females_sales_or_marketing, females_not]], index=index_emp, columns=columns_emp)
observed_emp

Sales or Marketing  Not Sales or Marketing
Male                 31680                  112434
Female               20863                   75147

In [98]:
chi2, p, degf, expected = stats.chi2_contingency(observed_emp)

print('Observed\n')
print(observed_emp.values)
print('---\nExpected\n')
print(expected)
print('---\n')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed

[[ 31680 112434]
 [ 20863  75147]]
---
Expected

[[ 31534.46511802 112579.53488198]
 [ 21008.53488198  75001.46511802]]
---

chi^2 = 2.1356
p     = 0.1439


#### <font color='red'>The two variables are independent</font>

### Is an employee's gender independent of whether or not they are or have been a manager?

$H_{0}$: Employee's gender is independent of whether or not they have been a manager

$H_{a}$: Employee's gender is not independent of whether or not they have been a manager

In [91]:
emp_manager_female = pd.read_sql('''select distinct departments.dept_name as department_name, concat(employees.first_name,' ',employees.last_name) as department_manager
from employees
join dept_manager
on dept_manager.emp_no = employees.emp_no
join departments
on departments.dept_no = dept_manager.dept_no
where employees.gender = 'F'
order by department_name;
''', employees_url)

print(emp_manager_female.shape)
print(emp_manager_female.dtypes)
emp_manager_female
emp_manager_female.department_manager.count()

(13, 2)
department_name       object
department_manager    object
dtype: object


13

In [90]:
emp_manager_male = pd.read_sql('''select distinct departments.dept_name as department_name, concat(employees.first_name,' ',employees.last_name) as department_manager
from employees
join dept_manager
on dept_manager.emp_no = employees.emp_no
join departments
on departments.dept_no = dept_manager.dept_no
where employees.gender = 'M'
order by department_name;
''', employees_url)

print(emp_manager_male.shape)
print(emp_manager_male.dtypes)
emp_manager_male
emp_manager_male['department_manager'].count()

(11, 2)
department_name       object
department_manager    object
dtype: object


11

In [99]:
male = (employees.gender == 'M').sum() - 11
female = (employees.gender != 'M').sum() - 13

In [100]:
index_emp2 = ['Male', 'Female']
columns_emp2 = ['Manager', 'Never Been Manager']
observed_emp2 = pd.DataFrame([[11, male], [13, female]], index=index_emp2, columns=columns_emp2)
observed_emp2

Manager  Never Been Manager
Male         11              144103
Female       13               95997

In [101]:
chi2, p, degf, expected = stats.chi2_contingency(observed_emp2)

print('Observed\n')
print(observed_emp2.values)
print('---\nExpected\n')
print(expected)
print('---\n')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed

[[    11 144103]
 [    13  95997]]
---
Expected

[[1.44039580e+01 1.44099596e+05]
 [9.59604204e+00 9.60004040e+04]]
---

chi^2 = 1.4644
p     = 0.2262


#### <font color='red'>The two variables are independent</font>