# Exercises

# Overview

## For each of the following questions, formulate a null and alternative hypothesis (be as specific as you can be), 
## then give an example of what a true positive, true negative, type I and type II errors would look like.

### Is the website redesign any good? 

### Rephrased: Has the click rate gone up, down, or stayed the same since the website redesign?
    
   **Null hypothesis:** The click rate on the website has remained the same since the redesign.
    
   **Alternative hypothesis:** The website redesign was terrible and had a negative affect on the click rate.
    
   **True Positive:** Null hypothesis rejected and website redisign has had a negative affect on the click rate.
    
   **True Negative:** Null hypothesis not rejected.  Website redisign had a positive affect on click rates.
    
   **Type 1 Error:** Results say that website redesign had a negative affect on click rates but actually didnt in reality.
    
   **Type 2 Error:** Results say that website redesign didn't have a negative affect but it actually did in reality.
    

### Is our television ad driving more sales?

### Rephrased: Have sales gone up, down, or stayed the same since the release of our adds?
    
   **Null hypothesis:** The adds have no proven causal affect on our sales.
    
   **Alternative hypothesis:** The adds have had a positive affect on our sales.
    
   **True Positive:** Adds have a positive affect on sales.
    
   **True Negative:** Adds aren't proven to have a positive affect on sales.
    
   **Type 1 Error:** Results say that adds have a positive affect while in reality it didn't.
    
   **Type 2 Error:** Results say that adds don't have a positive affect on sales while in reality it does.

### Has the network latency gone up since we switched internet service providers?

### Rephrased: How has our network latency changed since we switched internet service providers?
    
   **Null hypothesis:** The change of internet service provider has had no affect on our latency.
    
   **Alternative hypothesis:** The change of internet service provider has increased our latency.
    
   **True Positive:** Change of ISP increased latency.
    
   **True Negative:** No proof that change of ISP had the affect of increasing latency.
    
   **Type 1 Error:** Results say that change of ISP increased latency while in reality it did not.
    
   **Type 2 Error:** Results say that change of ISP had no affect on latency while in reality it did.

# T-Test

### Ace Realty wants to determine whether the average time it takes to sell homes is different for its two offices. A sample of 40 sales from office #1 revealed a mean of 90 days and a standard deviation of 15 days. A sample of 50 sales from office #2 revealed a mean of 100 days and a standard deviation of 20 days. Use a .05 level of significance.

In [1]:
import math
import numpy as np
from scipy import stats

In [2]:
stats.norm(90, 15).rvs(40)

array([ 93.37405966, 105.66211396,  79.22732827,  74.69366282,
        88.92590628,  83.49601626,  84.14415429,  94.92971954,
        80.99163513,  81.81942755,  92.53460549,  82.56231348,
       101.39725232,  96.6516706 ,  96.50036166,  86.50058586,
       115.05445248,  79.09293682, 100.94386566,  76.3396509 ,
        69.64759513,  88.85858486, 117.4152355 ,  89.65238486,
       104.70499254,  63.47600836,  96.9629738 ,  77.6861698 ,
       110.19200387,  87.37747823,  78.69935568,  60.94806683,
        93.40071715,  97.94175976, 110.01771052,  90.93409617,
        60.87267005,  81.18759581,  67.49169449,  78.61963004])

In [3]:
stats.norm(100, 20).rvs(50)

array([109.24436863,  91.06789046, 125.07079947, 100.46386092,
       126.91297288, 105.53488504, 109.318794  ,  77.112078  ,
       114.23628547,  79.05466068,  88.65865872,  92.39597728,
       106.61536781, 115.55464021,  76.45157111,  88.54996218,
       124.8042106 ,  89.52236587, 109.33149379,  85.11104451,
        63.99533723, 117.13057995, 113.58596395,  75.54776807,
       103.19404149,  96.97780832, 100.05334286,  87.81167333,
        93.56423133,  84.97457361, 117.3731537 ,  85.09291839,
       121.0232094 , 127.32503126,  95.36956612, 106.3061075 ,
        68.89928886, 100.38241633,  89.18526992,  82.18899979,
       133.44788934,  94.96039755,  97.06757479, 122.82891069,
       135.17525056,  74.96012242, 108.90086879, 119.5811282 ,
        94.83749808, 126.4682163 ])

In [4]:
α = .05 #level of signifigance

n1 = 40 #sales
n2 = 50 #sales

µ1 = 90 #days
µ2 = 100 #days

σ1 = 15 #days
σ2 = 20 #days

x1 = stats.norm(90, 15).rvs(40)
x2 = stats.norm(100, 20).rvs(50)

x̄1 = x1.mean()
x̄2 = x2.mean()

s1 = x1.std()
s2 = x2.std()

degf = n1 + n2 - 2

sp = math.sqrt(((n1 - 1)*(σ1 ** 2) + (n2 - 1)*(σ2 ** 2)) / (degf))

t = (x̄1 - x̄2) / (sp * math.sqrt(1/n1 + 1/n2))

standard_error = se = math.sqrt(s1**2 / n1 + s2**2 / n2)

In [5]:
p = stats.t(degf).cdf(t) * 2
p

0.00514274277249705

In [6]:
t

-2.869795290520093

In [7]:
stats.ttest_ind(x1, x2)

Ttest_indResult(statistic=-2.4734981347874037, pvalue=0.015300282345377983)

### Load the mpg dataset and use it to answer the following questions:

In [8]:
from pydataset import data

mpg = data('mpg')
mpg.head()

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
4         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
5         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

### Is there a difference in fuel-efficiency in cars from 2008 vs 1999?

In [9]:
# Fuel efficiency of cars from 1999

mpg_1999 = ((mpg.cty[mpg.year == 1999] + mpg.hwy[mpg.year == 1999]) / 2)

# Fuel efficiency of cars from 2008

mpg_2008 = (mpg.cty[mpg.year == 2008] + mpg.hwy[mpg.year == 2008])

stats.ttest_ind(mpg_1999, mpg_2008)

Ttest_indResult(statistic=-19.399034424839172, pvalue=1.815311826660654e-50)

### Are compact cars more fuel-efficient than the average car?

In [10]:
# Fuel efficiency of compact cars

mpg_compact = (mpg.cty[mpg['class'] == 'compact'] + mpg.hwy[mpg['class'] == 'compact'] / 2)

# Fuel efficiency of all cars

mpg_all = ((mpg.cty + mpg.hwy) / 2).mean()

stats.ttest_1samp(mpg_compact, mpg_all)

Ttest_1sampResult(statistic=18.624517190434428, pvalue=4.67400197211997e-23)

### Do manual cars get better gas mileage than automatic cars?

In [11]:
mpg.trans = mpg.trans.str[:-4]

In [12]:
manual_mpg = (mpg[mpg.trans == 'manual'].cty +  mpg[mpg.trans == 'manual'].hwy) / 2

In [13]:
auto_mpg = (mpg[mpg.trans == 'auto'].cty +  mpg[mpg.trans == 'auto'].hwy) / 2

In [14]:
stats.ttest_ind(auto_mpg, manual_mpg)

Ttest_indResult(statistic=-4.593437735750014, pvalue=7.154374401145683e-06)

# Correlation

### Use the telco_churn data. Does tenure correlate with monthly charges? Total charges? What happens if you control for phone and internet service?

In [102]:
import pandas as pd
data = pd.read_csv("Telco_Data.csv") 

data['monthly_charges'] = data['monthly_charges'].str.replace('$',' ').str.strip().str.replace(',','_').astype(float)

data.head()

customer_id  gender  is_senior_citizen partner dependents  phone_service  \
0  0002-ORFBO  Female                  0     Yes        Yes              1   
1  0003-MKNFE    Male                  0      No         No              2   
2  0004-TLHLJ    Male                  0      No         No              1   
3  0011-IGKFF    Male                  1     Yes         No              1   
4  0013-EXCHZ  Female                  1     Yes         No              1   

   internet_service  contract_type      payment_type  monthly_charges  ...  \
0                 1              1      Mailed check             65.6  ...   
1                 1              0      Mailed check             59.9  ...   
2                 2              0  Electronic check             73.9  ...   
3                 2              0  Electronic check             98.0  ...   
4                 2              0      Mailed check             83.9  ...   

  has_phone has_internet  has_phone_and_internet  partner_dependents  \
0      True         True                    True                   3   
1      True         True                    True                   0   
2      True         True                    True                   0   
3      True         True                    True                   1   
4      True         True                    True                   1   

   start_date  avg_monthly_charges  contract_type2     phone_service2  \
0      1/7/19               $65.92          1 Year           One Line   
1      1/7/19               $60.27  Month-to-Month  Two or More Lines   
2      6/7/19               $70.21  Month-to-Month           One Line   
3      9/7/18               $95.22  Month-to-Month           One Line   
4      7/7/19               $89.13  Month-to-Month           One Line   

   Internet_service2 End Date  
0                DSL  10/7/19  
1                DSL  10/7/19  
2        Fiber Optic  10/7/19  
3        Fiber Optic  10/7/19  
4        Fiber Optic  10/7/19  

[5 rows x 25 columns]

In [104]:
data['total_charges'] = data['total_charges'].astype(str)
data['total_charges'] = data['total_charges'].str.replace('$',' ').str.strip().str.replace(',','_').astype(float)



In [105]:
# data = data[data.total_charges != ' ']
# data.total_charges = data.total_charges.astype(float)
data = data[['monthly_charges', 'total_charges', 'Monthly_Tenure', 'Internet_service2', 'phone_service2']]

In [106]:
data

monthly_charges  total_charges  Monthly_Tenure    Internet_service2  \
0               65.60         593.30               9                  DSL   
1               59.90         542.40               9                  DSL   
2               73.90         280.85               4          Fiber Optic   
3               98.00        1237.85              13          Fiber Optic   
4               83.90         267.40               3          Fiber Optic   
5               69.40         571.45               8                  DSL   
6              109.70        7904.25              72          Fiber Optic   
7               84.65        5377.80              64          Fiber Optic   
8               48.20         340.35               7                  DSL   
9               90.45        5957.90              66                  DSL   
10              45.20        2460.55              54                  DSL   
11             116.80        8456.75              72          Fiber Optic   
12              68.95         351.50               5          Fiber Optic   
13             101.30        7261.25              72          Fiber Optic   
14              45.05        2560.10              57                  DSL   
15              95.75        6849.40              72          Fiber Optic   
16              61.25        1993.20              33                  DSL   
17              72.10          72.10               1          Fiber Optic   
18              62.70        2791.50              45                  DSL   
19              25.10          25.10               1                  DSL   
20              25.20        1306.30              52  No Internet Service   
21              94.10        1215.60              13          Fiber Optic   
22              83.75        1849.95              22          Fiber Optic   
23              19.85          57.20               3  No Internet Service   
24              20.35          76.35               4  No Internet Service   
25              30.50          30.50               1                  DSL   
26             103.70        5656.75              55          Fiber Optic   
27              20.40        1090.60              53  No Internet Service   
28              19.60         471.85              24  No Internet Service   
29              19.70        1396.90              71  No Internet Service   
30              91.20        3247.55              36          Fiber Optic   
31              20.45         900.90              44  No Internet Service   
32             115.80        7942.15              69          Fiber Optic   
33              20.55        1343.40              65  No Internet Service   
34              39.40         825.40              21                  DSL   
35              25.10        1070.15              43  No Internet Service   
36              89.80        4959.60              55          Fiber Optic   
37              94.75        5597.65              59          Fiber Optic   
38              20.30         224.50              11  No Internet Service   
39              75.75        1929.00              25          Fiber Optic   
40              49.25          91.10               2                  DSL   
41              78.20        2078.95              27                  DSL   
42              25.50         630.60              25  No Internet Service   
43              61.60        1611.00              26                  DSL   
44              45.00        1242.45              28                  DSL   
45              85.15        6316.20              74                  DSL   
46              51.45         727.85              14                  DSL   
47              99.25        3532.00              36          Fiber Optic   
48              44.30          44.30               1                  DSL   
49              94.20        2607.60              28          Fiber Optic   
50              81.25        5567.55              69                  DSL   
51

In [107]:
tenure = data.Monthly_Tenure
monthly_charges = data.monthly_charges
stats.ttest_ind(tenure, monthly_charges)

Ttest_indResult(statistic=-69.89334627096505, pvalue=0.0)

In [108]:
corr, p = stats.pearsonr(tenure, monthly_charges)
corr, p

(0.2471808461571538, 1.5602224848403675e-98)

### Use the employees database.



In [18]:
import pandas as pd
from env import user, host, password

def get_db_url(user, host, password, database):
    url = f'mysql+pymysql://{user}:{password}@{host}/{database}'
    return url

employees_url = get_db_url(user, host, password, database="employees")

employees = pd.read_sql('''SELECT
    e.*,
    datediff('2002-09-30', e.hire_date) tenure,
    t.title,
    t.from_date title_from,
    datediff('2002-09-30', t.from_date) t_tenure,
    et.titles,
    s.salary,
    s.from_date salary_from,
    datediff('2002-09-30', s.from_date) s_tenure,
    es.salaries
FROM
    employees e
JOIN 
    titles t 
    USING(emp_no)
JOIN 
    salaries s 
    USING(emp_no)
JOIN
    (SELECT 
        emp_no,
        count(*) titles
    FROM
        titles
    GROUP BY
        emp_no) et
    USING(emp_no)
JOIN
    (SELECT 
        emp_no,
        count(*) salaries
    FROM
        salaries
    GROUP BY
        emp_no) es
    USING(emp_no)
WHERE
    s.to_date > '2002-09-30'
    AND t.to_date > '2002-09-30';
''', employees_url)

print(employees.shape)
print(employees.dtypes)
employees.sample(5)

(240124, 15)
emp_no          int64
birth_date     object
first_name     object
last_name      object
gender         object
hire_date      object
tenure          int64
title          object
title_from     object
t_tenure        int64
titles          int64
salary          int64
salary_from    object
s_tenure        int64
salaries        int64
dtype: object


emp_no  birth_date first_name   last_name gender   hire_date  tenure  \
20543    35581  1957-02-27      Randi     Straney      M  1987-07-21    5550   
210122  462410  1957-12-29     Stella    Thombley      M  1986-02-11    6075   
3266     14036  1962-03-20     Bogdan      Schaad      F  1987-10-07    5472   
231689  489389  1952-06-18     Claude    Bonifati      F  1987-08-28    5512   
203593  454238  1960-11-22       Erez  Gluchowski      M  1990-08-22    4422   

                  title  title_from  t_tenure  titles  salary salary_from  \
20543      Senior Staff  1999-05-11      1238       2   77008  2002-05-09   
210122  Senior Engineer  1986-02-11      6075       1   77260  2002-02-07   
3266       Senior Staff  1992-10-06      3646       2   78670  2001-10-03   
231689  Senior Engineer  1991-08-05      4074       1   62945  2001-08-02   
203593         Engineer  1999-08-22      1135       2   58844  2001-08-19   

        s_tenure  salaries  
20543        144        10  
210122       235        17  
3266         362        15  
231689       424        11  
203593       407        12

### Is there a relationship between how long an employee has been with the company and their salary?

In [19]:
stats.ttest_ind(employees.t_tenure, employees.salary)

Ttest_indResult(statistic=-1965.290256976851, pvalue=0.0)

In [20]:
corr, p = stats.pearsonr(employees.t_tenure, employees.salary)
corr, p

(0.2928925355455215, 0.0)

p values is low because it is such a large population.  The higher the n, the smaller the p value.  With a higher number of n, the more we're able to detect very small affects.

### Is there a relationship between how long an employee has been with the company and the number of titles they have had?

In [21]:
stats.ttest_ind(employees.t_tenure, employees.titles)

Ttest_indResult(statistic=823.4102997009813, pvalue=0.0)

In [22]:
corr, p = stats.pearsonr(employees.t_tenure, employees.titles)
corr, p

(-0.3130073440315879, 0.0)

### Use the sleepstudy data. Is there a relationship between days and reaction time?

In [23]:
from pydataset import data
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

sleepstudy = data('sleepstudy')
sleepstudy.head()

Reaction  Days  Subject
1  249.5600     0      308
2  258.7047     1      308
3  250.8006     2      308
4  321.4398     3      308
5  356.8519     4      308

In [24]:
stats.ttest_ind(sleepstudy.Days, sleepstudy.Reaction)

Ttest_indResult(statistic=-69.93555875916752, pvalue=7.790453448409e-211)

In [25]:
corr, p = stats.pearsonr(sleepstudy.Days, sleepstudy.Reaction)
corr, p

(0.5352302262650253, 9.894096322214812e-15)

# Chi Square

### Use the following contingency table to help answer the question of whether using a macbook and being a codeup student are independent of each other.



|                       | Codeup Student | Not Codeup Student |   |   |
|-----------------------|----------------|--------------------|---|---|
| Uses A Macbook        | 49             | 20                 |   |   |
| Doesn't Use A MacBook | 1              | 30                 |   |   |
|                       |                |                    |   |   |

$H_{0}$: Whether or not someone uses a macbook is independent of being a codeup student

$H_{a}$: Whether or not someone uses a macbook is NOT independent of being a codeup student

In [26]:
index = ['Uses A Macbook', "Doesn't Use A Macbook"]
columns = ['Codeup Student', 'Not Codeup Student']

observed = pd.DataFrame([[49, 20], [1, 30]], index=index, columns=columns)
chi2, p, degf, expected = stats.chi2_contingency(observed)
print('Observed\n')
print(observed.values)
print('---\nExpected\n')
print(expected)
print('---\n')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed

[[49 20]
 [ 1 30]]
---
Expected

[[34.5 34.5]
 [15.5 15.5]]
---

chi^2 = 36.6526
p     = 0.0000


#### <font color='red'>The two variables are not independent</font>

### Choose another 2 categorical variables from the mpg dataset and perform a chi^2 contingency table test with them. Be sure to state your null and alternative hypotheses.

$H_{0}$: Whether or not the class of car is a compact is independent of whether or not it's an Audi.

$H_{a}$: Whether or not the class of car is a compact is NOT independent of whether or not it's an Audi.

In [27]:
# compact = (mpg['class'][mpg.manufacturer == 'audi'] == 'compact').sum()
# not_compact = (mpg['class'][mpg.manufacturer == 'audi'] != 'compact').sum()

compact = (mpg['class'] == 'compact').sum()
not_compact = (mpg['class'] != 'compact').sum()
audi = (mpg.manufacturer == 'audi').sum()
not_audi = (mpg.manufacturer != 'audi').sum()

In [28]:
index_mpg = ['Compact', 'Not A Compact']
columns_mpg = ['Audi', 'Not Audi']
observed_mpg = pd.DataFrame([[compact, not_compact], [audi, not_audi]], index=index_mpg, columns=columns_mpg)
observed_mpg

Audi  Not Audi
Compact          47       187
Not A Compact    18       216

In [29]:
chi2, p, degf, expected = stats.chi2_contingency(observed_mpg)

print('Observed\n')
print(observed_mpg.values)
print('---\nExpected\n')
print(expected)
print('---\n')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed

[[ 47 187]
 [ 18 216]]
---
Expected

[[ 32.5 201.5]
 [ 32.5 201.5]]
---

chi^2 = 14.0069
p     = 0.0002


#### <font color='red'>The two variables are not independent</font>

## Use the data from the employees database to answer these questions:

In [30]:
print(employees.shape)
print(employees.dtypes)
employees.sample(5)

(240124, 15)
emp_no          int64
birth_date     object
first_name     object
last_name      object
gender         object
hire_date      object
tenure          int64
title          object
title_from     object
t_tenure        int64
titles          int64
salary          int64
salary_from    object
s_tenure        int64
salaries        int64
dtype: object


emp_no  birth_date first_name    last_name gender   hire_date  tenure  \
21350    36592  1961-04-28    Tsvetan       Ghelli      F  1989-05-07    4894   
226907  483406  1959-10-26   Xiaoheng      Shrader      M  1985-10-15    6194   
173108  416173  1962-07-22    Lubomir  Seghrouchni      F  1988-06-14    5221   
46558    68018  1959-08-28     Filipp         Undy      F  1990-05-09    4527   
63340    89009  1964-01-16     Rosita       Varman      M  1992-06-09    3765   

                  title  title_from  t_tenure  titles  salary salary_from  \
21350   Senior Engineer  1995-10-29      2528       2   54778  2001-10-26   
226907     Senior Staff  1998-06-17      1566       1   44868  2002-06-16   
173108     Senior Staff  2000-05-04       879       2   62637  2002-05-02   
46558   Senior Engineer  1999-05-09      1240       2   73362  2002-05-06   
63340      Senior Staff  1997-06-09      1939       2   77698  2002-06-07   

        s_tenure  salaries  
21350        339        12  
226907       106         5  
173108       151        11  
46558        147        13  
63340        115        11

### Is an employee's gender independent of whether an employee works in sales or marketing? (only look at current employees)

$H_{0}$: Employee's gender is independent of whether an employee works in sales or marketing.

$H_{a}$: Employee's gender is not independent of whether an employee works in sales or marketing.

In [31]:
employees_female_by_department = pd.read_sql('''select departments.dept_no, departments.dept_name, count(employees.emp_no) as count
from departments
join dept_emp
on departments.dept_no = dept_emp.dept_no
join employees
on dept_emp.emp_no = employees.emp_no
where dept_emp.to_date = '9999-01-01' and gender = 'F'
group by departments.dept_name
order by dept_no;
''',employees_url)

print(employees_female_by_department.shape)
print(employees_female_by_department.dtypes)
employees_female_by_department

(9, 3)
dept_no      object
dept_name    object
count         int64
dtype: object


dept_no           dept_name  count
0    d001           Marketing   5864
1    d002             Finance   5014
2    d003     Human Resources   5147
3    d004          Production  21393
4    d005         Development  24533
5    d006  Quality Management   5872
6    d007               Sales  14999
7    d008            Research   6181
8    d009    Customer Service   7007

In [32]:
females_sales_or_marketing = 5864 +14999
females_not = employees_female_by_department['count'].sum() - females_sales_or_marketing
females_not

75147

In [33]:
employees_male_by_department = pd.read_sql('''select departments.dept_no, departments.dept_name, count(employees.emp_no) as count
from departments
join dept_emp
on departments.dept_no = dept_emp.dept_no
join employees
on dept_emp.emp_no = employees.emp_no
where dept_emp.to_date = '9999-01-01' and gender = 'M'
group by departments.dept_name
order by dept_no;
''',employees_url)

print(employees_male_by_department.shape)
print(employees_male_by_department.dtypes)
employees_male_by_department

(9, 3)
dept_no      object
dept_name    object
count         int64
dtype: object


dept_no           dept_name  count
0    d001           Marketing   8978
1    d002             Finance   7423
2    d003     Human Resources   7751
3    d004          Production  31911
4    d005         Development  36853
5    d006  Quality Management   8674
6    d007               Sales  22702
7    d008            Research   9260
8    d009    Customer Service  10562

In [34]:
males_sales_or_marketing = 8978 + 22702
males_not = employees_male_by_department['count'].sum() - males_sales_or_marketing
males_not

112434

In [35]:
sales_or_marketing = males_sales_or_marketing + females_sales_or_marketing

In [36]:
index_emp = ['Male', 'Female']
columns_emp = ['Sales or Marketing', 'Not Sales or Marketing']
observed_emp = pd.DataFrame([[males_sales_or_marketing, males_not], [females_sales_or_marketing, females_not]], index=index_emp, columns=columns_emp)
observed_emp

Sales or Marketing  Not Sales or Marketing
Male                 31680                  112434
Female               20863                   75147

In [37]:
chi2, p, degf, expected = stats.chi2_contingency(observed_emp)

print('Observed\n')
print(observed_emp.values)
print('---\nExpected\n')
print(expected)
print('---\n')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed

[[ 31680 112434]
 [ 20863  75147]]
---
Expected

[[ 31534.46511802 112579.53488198]
 [ 21008.53488198  75001.46511802]]
---

chi^2 = 2.1356
p     = 0.1439


#### <font color='red'>The two variables are independent</font>

### Is an employee's gender independent of whether or not they are or have been a manager?

$H_{0}$: Employee's gender is independent of whether or not they have been a manager

$H_{a}$: Employee's gender is not independent of whether or not they have been a manager

In [38]:
emp_manager_female = pd.read_sql('''select distinct departments.dept_name as department_name, concat(employees.first_name,' ',employees.last_name) as department_manager
from employees
join dept_manager
on dept_manager.emp_no = employees.emp_no
join departments
on departments.dept_no = dept_manager.dept_no
where employees.gender = 'F'
order by department_name;
''', employees_url)

print(emp_manager_female.shape)
print(emp_manager_female.dtypes)
emp_manager_female
emp_manager_female.department_manager.count()

(13, 2)
department_name       object
department_manager    object
dtype: object


13

In [39]:
emp_manager_male = pd.read_sql('''select distinct departments.dept_name as department_name, concat(employees.first_name,' ',employees.last_name) as department_manager
from employees
join dept_manager
on dept_manager.emp_no = employees.emp_no
join departments
on departments.dept_no = dept_manager.dept_no
where employees.gender = 'M'
order by department_name;
''', employees_url)

print(emp_manager_male.shape)
print(emp_manager_male.dtypes)
emp_manager_male
emp_manager_male['department_manager'].count()

(11, 2)
department_name       object
department_manager    object
dtype: object


11

In [40]:
male = (employees.gender == 'M').sum() - 11
female = (employees.gender != 'M').sum() - 13

In [41]:
index_emp2 = ['Male', 'Female']
columns_emp2 = ['Manager', 'Never Been Manager']
observed_emp2 = pd.DataFrame([[11, male], [13, female]], index=index_emp2, columns=columns_emp2)
observed_emp2

Manager  Never Been Manager
Male         11              144103
Female       13               95997

In [42]:
chi2, p, degf, expected = stats.chi2_contingency(observed_emp2)

print('Observed\n')
print(observed_emp2.values)
print('---\nExpected\n')
print(expected)
print('---\n')
print(f'chi^2 = {chi2:.4f}')
print(f'p     = {p:.4f}')

Observed

[[    11 144103]
 [    13  95997]]
---
Expected

[[1.44039580e+01 1.44099596e+05]
 [9.59604204e+00 9.60004040e+04]]
---

chi^2 = 1.4644
p     = 0.2262


#### <font color='red'>The two variables are independent</font>